### ISSUE TITLE
Where can I found userAuthKey?

### ISSUE THREAD

**Issue by malcommac** [KolektifLabs/onesignal-node#2]
I can find both AppID and REST API Key under Keys & IDs of the OneSignaal panel, but what about the userAuthKey?

**Comment by redexp** [comment]
Looks like you don't need `userAuthKey` if you have only one app, just ignore this option
```
app: {
  appId: 'ONESIGNAL APP ID',
  appAuthKey: 'REST API KEY'
}
```

**Comment by jakesyl** [comment]
Would love to see this betterdocumented
